name: Publish to npm and deploy demo

on:
  push:
    branches:
      - master
    paths:
      # require to change version number in package.json
      - 'package.json'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm i
      - run: npm run build
      - run: npm run deploy
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}